const POOLS_TRAITS = new Map([
    ['VEGAS',[
		{'Background': 'Baby blue'},
		{'Background': 'Vegas'},
		{'Background': 'Lunar new year blue'},
		{'Fur': 'Radioactive Pink'},
		{'Hat': 'Flat peak'},{'Mouth': 'Meh'},
		{'Mouth Decoration': 'Cigarette'},
		{'Glasses': 'Green laser'},
		{'Frame': 'Fairy lights'}]],
    ['ALLI',[
		{'Background': 'Red'},
		{'Background': 'Fireworks'},
		{'Fur': 'White'},
		{'Hat': 'Top hat red'},
		{'Mouth': 'Sad'},
		{'Mouth Decoration': 'Sick'},
		{'Glasses': 'Visor heart'},
		{'Frame': 'Fish bowl'}]],
    ['FARM',[
		{'Background': 'Khaki'},{'Background': 'Fireplace'},
		{'Fur': 'Gold'},
		{'Hat': 'Robin Hood'},
		{'Mouth Decoration': 'Flaming Hot'},
		{'Neck':'Blue Collar Gold Spikes'},
		{'Glasses': 'Visor Beam'},
		{'Frame': 'Poo'}]],
    ['SEA',[
		{'Background': 'Navy'},
		{'Fur': 'Holographic'},
		{'Hat': 'Reindeer'},
		{'Hat': 'Silver Crown'},
		{'Mouth Decoration': 'Snorkle'},
		{'Glasses': 'Eyepatch Right'},
		{'Glasses': 'Eyepatch Left'},
		{'Glasses': 'Red Laser'},
		{'Frame': 'Test Card'}]],
    ['ABC',[
		{'Background': 'Poo'},
		{'Fur': 'Baby Blue'},
		{'Hat': 'Police'},
		{'Hat': 'Holographic Hat'},
		{'Mouth': 'Hmmm'},
		{'Mouth Decoration': 'Tongue Out'},
		{'Glasses': 'Cyber Hosky 2.0'},
		{'Frame': 'Check Mate'}]],
    ['JACK',[
		{'Background': 'Peach'},
		{'Fur': 'Oscar'},
		{'Ear Decoration': 'Right Ring'},
		{'Hat': 'McDonalds'},
		{'Glasses': 'Blue Laser'},
		{'Frame': 'Playing Card'}]],
    ['PRIDE',[
		{'Background': 'Cyan'},
		{'Fur': 'Doberman'},
		{'Hat': 'Black Lunar New Year Hat'},
		{'Mouth': 'Ooooo'},
		{'Mouth Decoration': 'Rainbow Vomit'},
		{'Neck':'Neckerchief'},
		{'Glasses': 'Back To The Future'},
		{'Frame': 'Wernis'}]],
    ['FIKA',[
		{'Background': 'Yellow'},
		{'Fur': 'Tiger Fur'},
		{'Fur': 'Gold Tiger'},
		{'Fur': 'Imagine Dragons'},
		{'Fur': 'Panda'},
		{'Ear Decoration': 'Stud Right'},
		{'Hat': 'Trucker'},
		{'Mouth': 'Sad-ish'},
		{'Glasses': 'Lennon'},
		{'Frame': 'Astronaut'}]],
    ['HERO',[
		{'Background': 'Grey'},
		{'Fur': 'Blue Dog'},
		{'Hat': 'Hero'},
		{'Hat': 'Red Wooly Hat'},
		{'Hat': 'Blue Wooly Hat'},
		{'Hat': 'Hero 2'},
		{'Mouth Decoration': 'Goatee'},
		{'Neck':'Bowtie'),{'Neck':'Red Collar Gold Spikes'},
		{'Glasses': 'Visor Meh'},
		{'Frame': 'Wood'}]],
    ['PSYA',[
		{'Background': 'Red'},
		{'Fur': 'Yellow Dog'},
		{'Hat': 'Spin Top'},
		{'Hat': 'Santa Hat'},
		{'Hat': 'McDonalds Manager'},
		{'Mouth Decoration': 'Crumpet'},
		{'Glasses': 'Upside Down'},
		{'Frame': 'Frosty'}]],
    ['WOOF',[
		{'Background': 'Green'},
		{'Background': 'Snowfall'},
		{'Background': 'Beige'},
		{'Fur': 'Joker'},
		{'Ear Decoration': 'Double Right Rings'},
		{'Hat': 'Sweatband'},
		{'Hat': 'Blood Poo'},
		{'Mouth Decoration': 'Bone'},
		{'Neck':'Hawaiian'},
		{'Glasses': 'Thug Life'},
		{'Frame': 'Pernis Vs Wernis'}]],
    ['A3C',[
		{'Background': 'Late Night'},
		{'Fur': 'Pink'},
		{'Hat': 'Crown'},
		{'Mouth Decoration': 'Big Moustache'},
		{'Neck':'Blue Collar'},
		{'Glasses': 'Visor Dead'},
		{'Frame': 'Damien Hirst'}]],
    ['CHEF',[
		{'Background': 'Blue'},
		{'Fur': 'Bear'},
		{'Hat': 'Miner'},
		{'Hat': 'Black Lunar New Year Hat'},
		{'Mouth Decoration': 'Pizza'},
		{'Glasses': 'Gold Glasses'},
		{'Frame': 'Lunar New Year Gold'}]],
    ['ITZA',[
		{'Background': 'Mint'},
		{'Fur': 'Señor Josquí'},
		{'Ear Decoration': 'Double Stud Left'},
		{'Hat': 'Viking'},
		{'Hat': 'Elf Hat'},
		{'Glasses': 'Laser Visor'},
		{'Frame': 'Silver'}]],
    ['PSB',[
		{'Background': 'Prison'},
		{'Fur': 'Hoskasaur'},
		{'Ear Decoration': 'Stud Left'},
		{'Hat': 'Red Lunar New Year Hat'},
		{'Mouth': 'Happy'},
		{'Glasses': '3D Gloss'},
		{'Frame': 'Lunar New Year Wave'}]],
    ['QCPOL',[
		{'Background': 'Sunset'},
		{'Fur': 'Hoskrogu'},
		{'Ear Decoration': 'Double Stud Right'},
		{'Hat': 'Captain'},
		{'Mouth Decoration': 'Cigar'},
		{'Neck':'Red Collar'},
		{'Neck':'Chain'},
		{'Glasses': 'Visor'},
		{'Frame': 'Pernis'}]],
    ['SALT',[
		{'Background': 'Purple'},
		{'Fur': 'Hosky Droid'},
		{'Ear Decoration': 'Double Left Rings'},
		{'Hat': 'Top Hat Blue'},
		{'Hat': 'Tiger Hat'},
		{'Hat': 'Micky'},
		{'Glasses': '3D Glasses'},
		{'Frame': 'Candy Cane'}]]
]);
