const POOLS_TRAITS = new Map([
    ['A3C',[
		{'Background': 'Late Night'},
	        {'Background': 'Happy Trees - Jes Art'},
	        {'Background': 'Brickwall'},
	        {'Background': 'Consensus 2022 Uncommon'},
	        {'Background': 'Jackson Pollock'},
	        {'Background': 'Orange'},
	        {'Background': 'Stickers'},
	        {'Background': 'Neon'},
	        {'Background': 'Blue Grid'},
		{'Fur': 'Pink'},
		{'Fur': 'Coyote'},
		{'Fur': 'Coqui'},
		{'Ear Decoration': 'Beauty Mark'},
		{'Hat': 'Crown'},
		{'Hat': 'Mardis Gras Hat'},
		{'Hat': 'Trash Can Lid'},
		{'Hat': 'Forest Camo'},
		{'Hat': 'TBLH Hat'},
		{'Mouth Decoration': 'Big Moustache'},
		{'Neck':'Blue Collar'},
		{'Neck':'Vicar'},
		{'Neck':'The Fools Neck'},
		{'Glasses': 'Visor Dead'},
		{'Glasses': 'Fighter Pilot Glasses'},
		{'Frame': 'Damien Hirst'},
		{'Frame': ''},
		{'Frame': ''},
		{'Frame': ''},
		{'Frame': ''},
		{'Frame': ''}]],
    ['BONE',[
		{'Background': 'Poo'},
	        {'Background': 'This is Fine'},
	        {'Background': 'Ukraine'},
	        {'Background': 'Spamdle'},
	        {'Background': 'Busy'},
	        {'Background': 'Fluorescent Gradient'},
	        {'Background': 'Sunset Tones Gradient'},
	        {'Background': 'Livestream'},
	        {'Background': 'Obsidian'},
		{'Fur': 'Baby Blue'},
		{'Fur': 'Scruff'},
		{'Ear Decoration': 'Bandaged Ear Right'},
		{'Hat': 'Police'},
		{'Hat': 'Holographic Hat'},
		{'Hat': 'Blue Hat'},
		{'Hat': 'Beret'},
		{'Hat': 'Chef Hat'},
		{'Hat': 'Annie Hat'},
		{'Hat': 'Bloody Arrow'},
		{'Mouth': 'Hmmm'},
		{'Mouth Decoration': 'Tongue Out'},
		{'Neck':'Faux Rug Survivor'},
		{'Glasses': 'Cyber Hosky 2.0'},
		{'Glasses': 'Sunset Glasses'},
		{'Frame': 'Check Mate'},
		{'Frame': ''},
		{'Frame': ''},
		{'Frame': ''},
		{'Frame': ''},
		{'Frame': ''}]],
    ['LIDO',[
		{'Background': 'Red'},
		{'Background': 'Fireworks'},
	        {'Background': 'Pastel'},
	        {'Background': 'Salvador Hosky'},
	        {'Background': 'Bright Blue Green Gradient'},
		{'Fur': 'White'},
		{'Fur': 'Turtle'},
		{'Ear Decoration': 'Biggie Hair'},
		{'Hat': 'Top hat red'},
		{'Hat': 'Gold Ribbon Hat'},
		{'Hat': 'Pork Pie Hat'},
		{'Hat': 'Bicycle Helmet Orange'},
		{'Mouth': 'Sad'},
		{'Mouth Decoration': 'Sick'},
		{'Mouth Decoration': 'Bubblegum'},
		{'Neck':'Black and White Jester Neck'},
		{'Neck':'1rd Place Medal'},
		{'Glasses': 'Visor heart'},
		{'Glasses': 'Goggles'},
		{'Frame': 'Fish bowl'},
		{'Frame': ''},
		{'Frame': ''},
		{'Frame': ''},
		{'Frame': ''},
		{'Frame': ''},
		{'Frame': ''}]],
    ['CHEF',[
		{'Background': 'Blue'},
	        {'Background': 'Consensus 2022 Rare'},
	        {'Background': 'Black Radioactive Animated'},
	        {'Background': 'Underwater Animated'},
	        {'Background': 'Radioactive Yellow Animated'},
	        {'Background': 'Duplicate'},
		{'Fur': 'Bear'},
		{'Fur': 'Grey'},
		{'Ear Decoration': 'Bandaged Ear Left'},
		{'Hat': 'Miner'},
		{'Hat': 'Black Lunar New Year Hat'},
		{'Hat': 'Yellow Feather Hat'},
		{'Hat': 'Dune'},
		{'Mouth Decoration': 'Pizza'},
		{'Mouth Decoration': 'Bubblegum Popped'},
		{'Neck':'Rug Pool Bowl'},
		{'Glasses': 'Gold Glasses'},
		{'Glasses': 'Neistat'},
		{'Frame': 'Lunar New Year Gold'},
		{'Frame': ''},
		{'Frame': ''},
		{'Frame': ''},
		{'Frame': ''},
		{'Frame': ''},
		{'Frame': ''},
		{'Frame': ''}]],
    ['FARM',[
		{'Background': 'Khaki'},
	        {'Background': 'Fireplace'},
	        {'Background': 'Red Gradient'},
	        {'Background': 'Iris'},
	        {'Background': 'Green Purple Gradient'},
	        {'Background': 'Granite'},
	        {'Background': 'Cosmos'},
		{'Fur': 'Gold'},
		{'Fur': 'Ginger'},
		{'Ear Decoration': 'Candle Right'},
		{'Hat': 'Robin Hood'},
		{'Hat': 'Martian'},
		{'Hat': 'Karen'},
		{'Hat': 'Buffon Hat'},
		{'Hat': 'Prisoner 42069'},
		{'Hat': 'Afro'},
		{'Hat': 'Rainbow Hat'},
		{'Hat': 'Lawyer Wig'},
		{'Mouth Decoration': 'Flaming Hot'},
		{'Neck':'Blue Collar Gold Spikes'},
		{'Glasses': 'Visor Beam'},
		{'Glasses': 'Pilot Glasses Tinted'},
		{'Frame': 'Poo'},
		{'Frame': ''},
		{'Frame': ''}]],
    ['FIKA',[
		{'Background': 'Yellow'},
	        {'Background': 'Landscape'},
	        {'Background': 'FIAT'},
	        {'Background': 'Slate'},
	        {'Background': 'Press Start'},
	        {'Background': 'Field Gradient'},
		{'Fur': 'Tiger Fur'},
		{'Fur': 'Gold Tiger'},
		{'Fur': 'Imagine Dragons'},
		{'Fur': 'Panda'},
		{'Fur': 'Clay Face'},
		{'Ear Decoration': 'Stud Right'},
		{'Hat': 'Trucker'},
		{'Hat': 'Bison'},
		{'Hat': 'Robin Hood Error'},
		{'Hat': 'Racing Helmet'},
		{'Hat': 'Black and White Jester'},
		{'Hat': 'Santa Hat Error'},
		{'Hat': 'Tea Cup World\'s Best Coder'},
		{'Hat': 'Black Mask'},
		{'Hat': 'Dumpling'},
		{'Mouth': 'Sad-ish'},
		{'Mouth Decoration': 'Strawberry'},
		{'Neck':'Trash Can'},
		{'Glasses': 'Lennon'},
		{'Glasses': 'Asymmetrical Glasses'},
		{'Frame': 'Astronaut'},
		{'Frame': ''},
		{'Frame': ''}]],
    ['HERO',[
		{'Background': 'Grey'},
	        {'Background': 'Deep Green'},
	        {'Background': 'Dimalix'},
		{'Fur': 'Blue Dog'},
		{'Fur': 'Skull'},
		{'Fur': 'NSFW'},
		{'Ear Decoration': 'White Earphones'},
		{'Hat': 'Hero'},
		{'Hat': 'Red Wooly Hat'},
		{'Hat': 'Blue Wooly Hat'},
		{'Hat': 'Hero 2'},
		{'Hat': 'Cowboy Hero'},
		{'Mouth Decoration': 'Goatee'},
		{'Neck':'Bowtie'},
		{'Neck':'Red Collar Gold Spikes'},
		{'Glasses': 'Visor Meh'},
		{'Glasses': 'Stitches'},
		{'Glasses': 'Hero Mask'},
		{'Frame': 'Wood'},
		{'Frame': ''},
		{'Frame': ''}]],
    ['ITZA',[
		{'Background': 'Mint'},
	        {'Background': 'Full Moon'},
	        {'Background': 'Light Speed'},
	        {'Background': 'Gold Frameception'},
	        {'Background': 'Consensus 2022 Common'},
	        {'Background': 'GN'},
	        {'Background': 'Highly Classified'},
	        {'Background': 'GM'},
		{'Fur': 'Señor Josquí'},
		{'Fur': 'Flaming Hot'},
		{'Fur': 'Hosky Sticker'},
		{'Fur': 'Cerberosky'},
		{'Ear Decoration': 'Double Stud Left'},
		{'Hat': 'Viking'},
		{'Hat': 'Elf Hat'},
		{'Hat': 'King Tutankhamun'},
		{'Hat': 'Silver Crown Error'},
		{'Hat': 'Miner Error'},
		{'Hat': 'Flat Peak Error'},
		{'Hat': 'Elf Hat Error'},
		{'Hat': 'Bandana Error'},
		{'Hat': 'Viking Error'},
		{'Hat': 'Top Hat Blue Error'},
		{'Hat': 'Party Hat'},
		{'Hat': 'Head Wrap'},
		{'Mouth Decoration': 'Burgundy Moustache'},
		{'Neck':'Diamond Chain'},
		{'Neck':'Robot Bowtie'},
		{'Neck':'Green Poncho'},
		{'Glasses': 'Laser Visor'},
		{'Glasses': 'Yellow Laser Error'},
		{'Glasses': 'Green Laser Error'},
		{'Glasses': 'Back To The Future Error'},
		{'Glasses': 'Red Laser Error'},
		{'Glasses': 'Blue Laser Error'},
		{'Glasses': 'Visor Animated'},
		{'Glasses': 'Pilot Glasses Classic'},
		{'Frame': 'Silver'},
		{'Frame': ''},
		{'Frame': ''}]],
    ['JACK',[
		{'Background': 'Peach'},
	        {'Background': 'Wernis'},
	        {'Background': 'Epilogue'},
	        {'Background': 'Pernis'},
	        {'Background': 'Notepad'},
		{'Fur': 'Oscar'},
		{'Fur': 'Charles Mask'},
		{'Fur': 'Glow In The Dark Skull'},
		{'Ear Decoration': 'Right Ring'},
		{'Hat': 'McDonalds'},
		{'Hat': 'Sombrero'},
		{'Hat': 'Tea Cup'},
		{'Hat': 'Rob Boss'},
		{'Hat': 'McDonalds Error'},
		{'Hat': 'Captain Error'},
		{'Hat': 'Top Hat Red Error'},
		{'Hat': 'Crown Error'},
		{'Hat': 'Hero Error'},
		{'Hat': 'Poo Hat Error'},
		{'Hat': 'Hero 2 Error'},
		{'Hat': 'Gladiator Mask'},
		{'Mouth Decoration': 'Handlebar Moustache'},
		{'Neck':'2st Place Medal'},
		{'Neck':'1rd Chain'},
		{'Neck':'Poo Bowtie'},
		{'Neck':'Blue Bowtie'},
		{'Neck':'Bubblebath'},
		{'Neck':'Trash Can'},
		{'Glasses': 'Blue Laser'},
		{'Glasses': 'Eyepatch Right Error'},
		{'Glasses': 'Upside Down Error'},
		{'Glasses': 'Eyepatch Left Error'},
		{'Glasses': '3D Gloss Error'},
		{'Glasses': 'Retro Rainbow Eyes'},
		{'Glasses': 'Eyes Patched Error'},
		{'Glasses': 'Thug Life Error'},
		{'Glasses': 'Dude Error'},
		{'Glasses': 'Love Error'},
		{'Frame': 'Playing Card'},
		{'Frame': ''},
		{'Frame': ''}]],
    ['PRIDE',[
		{'Background': 'Cyan'},
	        {'Background': 'Pop Art'},
		{'Fur': 'Doberman'},
		{'Fur': 'LED'},
		{'Ear Decoration': 'Candle Middle'},
		{'Hat': 'Black Lunar New Year Hat'},
		{'Hat': 'Fez'},
		{'Hat': 'Dank Hat'},
		{'Mouth': 'Ooooo'},
		{'Mouth Decoration': 'Rainbow Vomit'},
		{'Neck':'Neckerchief'},
		{'Glasses': 'Back To The Future'},
		{'Glasses': 'Broken Pilot Glasses'},
		{'Frame': 'Wernis'},
		{'Frame': ''},
		{'Frame': ''}]],
    ['PSB',[
		{'Background': 'Prison'},
	        {'Background': 'Matrix'},
	        {'Background': 'Blue Stepped Gradient'},
		{'Fur': 'Hoskasaur'},
		{'Fur': 'Knitted'},
		{'Fur': 'Crazy Mary'},
		{'Ear Decoration': 'Stud Left'},
		{'Hat': 'Red Lunar New Year Hat'},
		{'Hat': 'HoskyMando'},
		{'Hat': 'Red Wooly Hat Error'},
		{'Hat': 'Squid Game Triangle'},
		{'Hat': 'Reindeer Error'},
		{'Hat': 'Horns'},
		{'Mouth': 'Happy'},
		{'Mouth Decoration': 'Fighter Pilot Mask'},
		{'Neck':'Blue Poncho'},
		{'Glasses': '3D Gloss'},
		{'Frame': 'Lunar New Year Wave'},
		{'Frame': ''}]],
    ['PSYA',[
		{'Background': 'Red'},
	        {'Background': 'Black Radioactive'},
	        {'Background': 'Carbon Fiber'},
	        {'Background': 'Radioactive Yellow'},
	        {'Background': 'Blue Yellow Gradient'},
		{'Fur': 'Yellow Dog'},
		{'Fur': 'Radioactive Orange'},
		{'Fur': 'Family'},
		{'Ear Decoration': 'Diamond Stud'},
		{'Hat': 'Spin Top'},
		{'Hat': 'Santa Hat'},
		{'Hat': 'McDonalds Manager'},
		{'Hat': 'Purple Hat'},
		{'Hat': 'Fighter Pilot'},
		{'Mouth Decoration': 'Crumpet'},
		{'Neck':'Gold Bowtie'},
		{'Glasses': 'Upside Down'},
		{'Frame': 'Frosty'},
		{'Frame': ''},
		{'Frame': ''}]],
    ['QCPOL',[
		{'Background': 'Sunset'},
	        {'Background': 'Morning Gradient'},
		{'Fur': 'Hoskrogu'},
		{'Fur': 'Frankenhosk'},
		{'Ear Decoration': 'Double Stud Right'},
		{'Hat': 'Captain'},
		{'Hat': 'Squid Game Square Error'},
		{'Hat': 'Squid Game Circle Error'},
		{'Hat': 'Squid Game Triangle Error'},
		{'Hat': 'Squid Game'},
		{'Hat': 'Third Ear Green'},
		{'Hat': 'Squid Game Error'},
		{'Hat': 'Pumpkin'},
		{'Hat': 'Pumpkin 2'},
		{'Mouth Decoration': 'Cigar'},
		{'Neck':'Red Collar'},
		{'Neck':'Chain'},
		{'Glasses': 'Visor'},
		{'Frame': 'Pernis'},
		{'Frame': ''}]],
    ['SALT',[
		{'Background': 'Purple'},
	        {'Background': 'Orchid'},
		{'Fur': 'Hosky Droid'},
		{'Fur': 'Original OAP'},
		{'Ear Decoration': 'Double Left Rings'},
		{'Hat': 'Top Hat Blue'},
		{'Hat': 'Tiger Hat'},
		{'Hat': 'Micky'},
		{'Hat': 'YOLO Hat'},
		{'Hat': 'Desert Camo'},
		{'Mouth Decoration': 'Beard'},
		{'Neck':'Hosk Chain'},
		{'Glasses': '3D Glasses'},
		{'Glasses': 'Monocle'},
		{'Frame': 'Candy Cane'},
		{'Frame': ''}]],
    ['SEA',[
		{'Background': 'Navy'},
	        {'Background': 'Green Gradient'},
	        {'Background': 'Extra Stank'},
	        {'Background': 'Ganja'},
	        {'Background': 'Blue Purple Gradient'},
	        {'Background': 'Jes Art'},
		{'Fur': 'Holographic'},
		{'Fur': 'Red Tiger'},
		{'Fur': 'Hoskytwo'},
		{'Fur': 'Unknown'},
		{'Fur': 'Ghosky'},
		{'Fur': 'Cardoggo'},
		{'Fur': 'Vasil Mask'},
		{'Fur': 'War Paint'},
		{'Ear Decoration': 'Double Bandaged Ears'},
		{'Hat': 'Reindeer'},
		{'Hat': 'Silver Crown'},
		{'Hat': 'Hosk Cap'},
		{'Hat': 'Halo'},
		{'Hat': 'Neon Sphinx Hat'},
		{'Hat': 'Trent Barnes'},
		{'Mouth Decoration': 'Snorkle'},
		{'Neck':'Cone'},
		{'Glasses': 'Eyepatch Right'},
		{'Glasses': 'Eyepatch Left'},
		{'Glasses': 'Red Laser'},
		{'Glasses': 'Tears'},
		{'Frame': 'Test Card'},
		{'Frame': 'Flies'},
		{'Frame': 'Flies Animated'}]],
    ['VEGAS',[
		{'Background': 'Baby blue'},
		{'Background': 'Vegas'},
		{'Background': 'Lunar new year blue'},
	        {'Background': 'Underwater'},
	        {'Background': 'April Fools'},
	        {'Background': 'Neon Pink Gradient'},
	        {'Background': 'Mint Gradient'},
		{'Fur': 'Radioactive Pink'},
		{'Fur': 'Banksy'},
		{'Fur': 'Cardano Whale'},
		{'Fur': 'Werewolf'},
		{'Fur': 'Ghost Chain'},
		{'Fur': 'Vegas Mask'},
		{'Ear Decoration': 'Dizzy'},
		{'Hat': 'Flat peak'},
		{'Hat': 'Micky Error'},
		{'Hat': 'Blood Poo Error'},
		{'Hat': 'McDonalds Manager Error'},
		{'Hat': 'HoskyFett'},
		{'Hat': 'Squid Game Circle'},
		{'Hat': 'Holographic Hat Error'},
		{'Hat': 'Squid Game Square'},
		{'Hat': 'King Tutankhamun Error'},
		{'Hat': 'The Fools Hat'},
		{'Hat': 'Splitting Headache'},
		{'Hat': 'HBI Hat'},
	        {'Mouth': 'Meh'},
		{'Mouth Decoration': 'Cigarette'},
		{'Neck':'SlumDogeEx-Millionaire'},
		{'Glasses': 'Green laser'},
		{'Glasses': 'Heads-Up Display'},
		{'Glasses': 'Late Night Glasses'},
		{'Frame': 'Fairy lights'},
		{'Frame': 'Ded'}]],
    ['WOOF',[
		{'Background': 'Green'},
		{'Background': 'Snowfall'},
		{'Background': 'Beige'},
	        {'Background': 'Light Blue Gradient'},
	        {'Background': 'Hosky Blue Gradient'},
	        {'Background': 'FIN'},
		{'Fur': 'Joker'},
		{'Fur': 'Original Retired'},
		{'Ear Decoration': 'Double Right Rings'},
		{'Hat': 'Sweatband'},
		{'Hat': 'Blood Poo'},
		{'Hat': 'Sweatband 2'},
		{'Hat': 'Cork Hat'},
		{'Hat': 'Sphinx Hat'},
		{'Hat': 'FUD Cap'},
		{'Hat': 'Paper Bag'},
		{'Mouth Decoration': 'Bone'},
		{'Neck':'Hawaiian'},
		{'Neck':'Black Bowtie'},
		{'Glasses': 'Thug Life'},
		{'Glasses': 'Upside Down Right Way Up'},
		{'Frame': 'Pernis Vs Wernis'},
		{'Frame': 'Golden Shine'}]],
    ['NANI',[
		{'Background': 'Dark Black'},
		{'Background': 'Sahara'},
		{'Fur': 'X-Ray'},
		{'Fur': 'Ghost'},
		{'Fur': 'Radioactive Green'},
		{'Fur': 'Grinch'},
		{'Fur': 'Fox'}
		{'Ear Decoration': 'Red Earphones'},
		{'Hat': 'Poo Hat'},
		{'Hat': 'Red Lunar New Year Hat'},
		{'Hat': 'We Need You'},
		{'Hat': 'Mohican'},
		{'Hat': 'Stay Palm'},
		{'Hat': 'Stay Palm Gold'},
		{'Mouth Decoration': 'Tooth'},
		{'Neck':'Doggy Bowl'},
		{'Glasses': 'Yellow Laser'},
		{'Glasses': 'Wipers'},
		{'Frame': 'Warning'},
		{'Frame': 'Spinning Bowtie'}]]
]);
